CFLAGS=-ggdb -Wall # compilation flags - language standard etc.
LDLIBS=-lm # additional libraries

zadanie_0 : zadanie_0.c
zadanie_1 : zadanie_1.c
zadanie_2 : zadanie_2.c
zadanie_3 : zadanie_3.c
zadanie_4 : zadanie_4.c
zadanie_5 : zadanie_4.c

clean:
	rm -f *.o zadanie_0 zadanie_1 zadanie_2 zadanie_3 zadanie_4 zadanie_5