CFLAGS=-ggdb -Wall # compilation flags - language standard etc.
LDLIBS=-lm -ggdb   # additional libraries

all: zadanie_0 zadanie_1 zadanie_2 zadanie_3 zadanie_4

clean:
	rm -f *.o zadanie_0 zadanie_1 zadanie_2 zadanie_3 zadanie_4 zadanie_5