CFLAGS=-Wall # compilation flags - language standard etc.
LDLIBS=-lm # additional libraries

all: hello_world ansi roots_2 power_sums # first command is default - input only "make"

clean:
	rm -f a.out hello_world ansi roots_2 power_sums