CFLAGS=-Wall # compilation flags - language standard etc.
LDLIBS=-lm # additional libraries

all: ansi roots_2 power_sums # first command is default - input only "make"

clean:
	rm -f a.out ansi roots_2 power_sums